# inputs.conf — Splunk Universal Forwarder
# Deploy to: C:\Program Files\SplunkUniversalForwarder\etc\system\local\inputs.conf
# Apply to: DC01 and WIN10-01

[WinEventLog://Security]
index = wineventlog
disabled = 0

[WinEventLog://System]
index = wineventlog
disabled = 0

[WinEventLog://Application]
index = wineventlog
disabled = 0

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
index = wineventlog
disabled = 0
