# outputs.conf — Splunk Universal Forwarder
# Deploy to: C:\Program Files\SplunkUniversalForwarder\etc\system\local\outputs.conf
# Apply to: DC01 and WIN10-01

[tcpout]
defaultGroup = splunk-server

[tcpout:splunk-server]
server = 192.168.10.40:9997
